WestdalePharmacyApp/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WestdalePharmacyApp.Models;

namespace WestdalePharmacyApp.Controllers
{
    public class ClientsController : Controller
    {
        private UserManager<ApplicationUser> userManager;

        public ClientsController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            var users = userManager.Users;
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string value)
        {
            var user = from n in userManager.Users select n;


            ViewBag.SearchedUser = value;

            if (!string.IsNullOrEmpty(value))
            {
                user = user.Where(a => a.LastName.Contains(value) || a.PhoneNumber.Contains(value));
            }

            return View(await user.AsNoTracking().ToListAsync());

        }



        // GET: ClientController/Details/5
        public async Task<ActionResult> Details(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var user = await userManager.Users.FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
    }
}

WestdalePharmacyApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WestdalePharmacyApp.Models;

namespace WestdalePharmacyApp.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WestdalePharmacyApp/Controllers/PrescriptionsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WestdalePharmacyApp.Data;
using WestdalePharmacyApp.IServices;
using WestdalePharmacyApp.Models;

namespace WestdalePharmacyApp.Controllers
{
    [Authorize]
    public class PrescriptionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;
        private readonly SignInManager<ApplicationUser> _signInManager;


        private IPrescriptionService _prescriptionService = null;

        public PrescriptionsController(
            ApplicationDbContext context,
            IPrescriptionService prescriptionService,
            UserManager<ApplicationUser> userManager,
            IEmailSender emailSender,
            SignInManager<ApplicationUser> signInManager
            )
        {
            _context = context;
            _prescriptionService = prescriptionService;
            _userManager = userManager;
            _emailSender = emailSender;
            _signInManager = signInManager;
        }

        [Authorize(Roles = "Client")]
        // GET: Prescriptions
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var applicationDbContext = _context.Prescriptions.Where(o => o.UserId == user.Id)
                .Include(p => p.User);

            return View(await applicationDbContext.ToListAsync());
        }

        [Authorize(Roles = "Client")]
        // GET: Prescriptions/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prescription = await _context.Prescriptions
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PrescriptionId == id);
            if (prescription == null)
            {
                return NotFound();
            }

            return View(prescription);
        }

        [Authorize(Roles = "Client")]
        // GET: Prescriptions/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        [Authorize(Roles = "Client")]
        // POST: Prescriptions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PrescriptionId,Refill,ImageFile,Status,CreationTime,UpdatedTime,SpecialInstruction,UserId")] Prescription prescription)
        {
            if (ModelState.IsValid)
            {

                

                prescription.PrescriptionId = Guid.NewGuid();
                _context.Add(prescription);
                await _context.SaveChangesAsync();

                
                return RedirectToAction(nameof(Index));

            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", prescription.UserId);
            return View(prescription);
        }


        [Authorize(Roles = "Client")]
        // GET: Prescriptions/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prescription = await _context.Prescriptions.FindAsync(id);
            if (prescription == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", prescription.UserId);
            return View(prescription);
        }

        [Authorize(Roles = "Client")]
        // POST: Prescriptions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("PrescriptionId,Refill,ImageFile,Status,CreationTime,UpdatedTime,SpecialInstruction,UserId")] Prescription prescription)
        {

            if (id != prescription.PrescriptionId)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            var tempPrescription = await _context.Prescriptions.AsNoTracking().Where(o => o.PrescriptionId == id).FirstOrDefaultAsync();             prescription.ImageFile = tempPrescription.ImageFile;
            prescription.UpdatedTime = DateTimeOffset.Now;
            prescription.ImageFile = tempPrescription.ImageFile;
            prescription.CreationTime = tempPrescription.CreationTime;
            prescription.Status = tempPrescription.Status;
            prescription.RefillAvailable = tempPrescription.RefillAvailable;
            prescription.UserId = user.Id;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prescription);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PrescriptionExists(prescription.PrescriptionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", prescription.UserId);
            return View(prescription);
        }

        [Authorize(Roles = "Client")]
        // GET: Prescriptions/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prescription = await _context.Prescriptions
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PrescriptionId == id);
            if (prescription == null)
            {
                return NotFound();
            }

            return View(prescription);
        }

        [Authorize(Roles = "Client")]
        // POST: Prescriptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var prescription = await _context.Prescriptions.FindAsync(id);
            _context.Prescriptions.Remove(prescription);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PrescriptionExists(Guid id)
        {
            return _context.Prescriptions.Any(e => e.PrescriptionId == id);
        }


        [HttpPost]
        public async Task<string> SaveFile(FileUpload fileObj)
        {
            var user = await _userManager.GetUserAsync(User);

            

            Prescription prescription = JsonConvert.DeserializeObject<Prescription>(fileObj.Prescription);
            if (fileObj.file==null)
            {
                return "Failed";
            }
            if (fileObj.file.Length > 0)
            {
                using (var ms = new MemoryStream())
                {
                    fileObj.file.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    prescription.ImageFile = fileBytes;

                    prescription.UserId = user.Id;
                    prescription.CreationTime = DateTimeOffset.Now;
                    prescription = _prescriptionService.Save(prescription);

                    if (prescription.PrescriptionId != null)
                    {

                        var roleUser = await _context.Roles.SingleOrDefaultAsync(m => m.Name == "Admin");
                        var adminUserId = await _context.UserRoles.Where(m => m.RoleId == roleUser.Id).FirstOrDefaultAsync();
                        var adminUser = await _context.Users.Where(o => o.Id == adminUserId.UserId).FirstOrDefaultAsync();
                        await _emailSender.SendEmailAsync(adminUser.Email, "New Prescription Request ", user.FirstName + " " + user.LastName + " requested prescription...");

                        await _emailSender.SendEmailAsync(user.Email, "Prescription Request", 
                            $"Dear <b> {user.FirstName} {user.LastName} </b> <br> Thank you for uploading your prescription. <br>We succesfully receieved your prescription at {prescription.CreationTime.ToString("HH:mm")} on {DateTime.Today.ToString("dd-MM-yyyy")} a one of our team member will contact you within the next 24 hours with more details. <br><br>Thank you,<br> Westdale Pharmacy Team");
                        return "Thank you! Your prescription has been successfully submitted!";

                    }
                }
            }
            return "Failed";
        }

        [HttpGet]
        public JsonResult GetSavedPrescription()
        {
            var prescription = _prescriptionService.GetSavedPrescription();
            prescription.ImageFile = this.GetImage(Convert.ToBase64String(prescription.ImageFile));
            return Json(prescription);

        }

        private byte[] GetImage(string sBase64String)
        {
            byte[] bytes = null;
            if (!string.IsNullOrEmpty(sBase64String))
            {

WestdalePharmacyApp/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
	ViewData["Title"] = "Home Page";
}
@if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
		{
	//admin
<div class="card-deck">
	<div class="card"  >
		<a asp-controller="Clients" asp-action="Index">
			<img class="card-img-top" src="~/images/profile.png" alt="Profile">
			<div class="card-body">
				<h5 class="card-title">View All Clients </h5>

			</div>
		</a>
	</div>
	<div class="card">
		<a asp-controller="Prescriptions" asp-action="IndexA">
			<img class="card-img-top" src="~/images/prescription.png" alt="Perscription">
			<div class="card-body">
				<h5 class="card-title">View Prescription Request</h5>

			</div>
		</a>
	</div>
	<div class="card">
		<a  asp-controller="MessagesForAdmin" asp-action="Index">
			<img class="card-img-top" src="~/images/message.png" alt="Message">
			<div class="card-body">
				<h5 class="card-title">New Messages </h5>
	
			</div>
		</a>
	</div>
</div>

}
@if (SignInManager.IsSignedIn(User) && User.IsInRole("Client"))
{
	//Client
<div class="card-deck">
	<div class="card" >
		<a asp-controller="MessagesForUser" asp-action="Index">
			<img class="card-img-top" src="~/images/message.png" alt="Message" >
			<div class="card-body">
				<h5 class="card-title">Send New Message </h5>
			</div>
		</a>
	</div>
	<div class="card" >
		<a asp-controller="Prescriptions" asp-action="Create">
			<img class="card-img-top" src="~/images/medical-prescription.png" alt="Create Prescription" >
			<div class="card-body">
				<h5 class="card-title">Send New Prescription</h5>
			</div>
		</a>
	</div>
	<div class="card"  >
		<a asp-controller="Prescriptions" asp-action="Index">
			<img class="card-img-top" src="~/images/prescription.png" alt="Pescription Index">
			<div class="card-body">
                <h5 class="card-title">Prescription History </h5>
		
			</div>
		</a>
	</div>
	
	<div class="card">
		<a asp-area="Identity" asp-page="/Account/Manage/Index">
			<img class="card-img-top" src="~/images/profile.png" alt="Profile">
			<div class="card-body">
				<h5 class="card-title">Update Information</h5>

			</div>
		</a>
</div>
</div>
}

@if (!SignInManager.IsSignedIn(User))
{
	<div class="text-center">
		<h1 class="display-4">Welcome</h1>
		<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
				<li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
				<li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
				<li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
			</ol>
			<div class="carousel-inner">
				<div class="carousel-item active">
					<img src="~/images/stethoscope.jpg" class="d-block w-100" alt="stesthoscope">
					<div class="carousel-caption d-none d-md-block">
						<h5>Send us your prescription </h5>
						<p>We will fill it for you.</p>
					</div>
				</div>
				<div class="carousel-item">
					<img src="~/images/vaccine.png" class="d-block w-100" alt="Vaccine">
					<div class="carousel-caption d-none d-md-block">
						<h5>Book your flu shot</h5>
						<p>Just send us a message and we will have ready for you! </p>
					</div>
				</div>
				<div class="carousel-item">
					<img src="~/images/mobileImage.jpg" class="d-block w-100" alt="Mobile Image">
					<div class="carousel-caption d-none d-md-block">
						<h5>Mobile Friendly!</h5>
						<p>We are just a click away!</p>
					</div>
				</div>
				<div class="carousel-item">
					<img src="~/images/pills.png" class="d-block w-100" alt="Pills">
					<div class="carousel-caption d-none d-md-block">
						<h5>Send us your prescription</h5>
						<p>We will have your prescription ready for you! </p>
					</div>
				</div>
			</div>
			<a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div>
	</div>
}